<a href="https://colab.research.google.com/github/Amritpal-nitj/Tensorflow/blob/main/addsubmuldiv.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

tf.math

TensorFlow provides a variety of math functions including:

. Basic arithmetic operators and trigonometric functions

· Special math functions (like: tf.math.igamma and tf.math.zeta)

. Complex number functions (like: tf.math.imag and tf.math.angle)

· Reductions and scans (like: tf.math.reduce_mean and tf.math.cumsum)

· Segment functions (like: tf.math.segment_sum)

#HOW TO DO ADDITION OF TENSORS IN TENSORFLOW
tf.add() :element wise addition
it can add list,tuple ,scalar
tf variable/constant/placeholder/sparsematrix with each other and with scalar and list/tuple.

In [15]:
import tensorflow as tf
import numpy as np

#Scalar Adding

In [1]:
a=10
b=20

In [2]:
a+b

30

In [5]:
tf.add(a,b)

<tf.Tensor: shape=(), dtype=int32, numpy=30>

ADD 2 LISTS

In [6]:
l1=[4,5,6]
l2=[2,6,9]
tf.add(l1,l2)    #size same hona chahiye

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 6, 11, 15], dtype=int32)>

add 2 tuple

In [8]:
t1=(4,5,6)
t2=(2,6,9)
tf.add(t1,t1)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 8, 10, 12], dtype=int32)>

add tuple/list with scalar

In [9]:
tf.add(l1,a)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([14, 15, 16], dtype=int32)>

Add 2 numpy array

In [10]:
na1=np.array([4,5,6])
na2=np.array([2,6,9])
tf.add(na1,na2)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([ 6, 11, 15])>

add numpy array with scalar

In [11]:
tf.add(na1,a)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([14, 15, 16])>

Add numpy array with single element np array

In [16]:
n1=np.array([4,5,6])    #yes possible
n2=np.array([2])
n3=np.array([[3]])
tf.add(n1,n2)


<tf.Tensor: shape=(1, 3), dtype=int64, numpy=array([[7, 8, 9]])>

In [17]:
tf.add(n1,n3)  #output also 2d

<tf.Tensor: shape=(1, 3), dtype=int64, numpy=array([[7, 8, 9]])>

#add 2 Tf constants

In [18]:
tfc1=tf.constant([4,5,6])
tfc2=tf.constant([2,6,9])
tf.add(tfc1,tfc2)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 6, 11, 15], dtype=int32)>

add tf constant with scalar

In [19]:
tf.add(tfc1,a)  #yes possible

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([14, 15, 16], dtype=int32)>

In [22]:
tf.Variable([4,5,6])  #variable

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([4, 5, 6], dtype=int32)>

In [25]:
tf.constant([2,6,9])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 6, 9], dtype=int32)>

add 2 tf variable

In [21]:
tfv1=tf.Variable([4,5,6])
tfv2=tf.Variable([2,6,9])
tf.add(tfv1,tfv2)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 6, 11, 15], dtype=int32)>

add tf variable with scalar

In [20]:
tfv1=tf.Variable([4,5,6])
tf.add(tfv1,a)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([14, 15, 16], dtype=int32)>

#ADD2 NUMPY ARRAY OF DIFF SHAPE

In [28]:
x=np.ones(6).reshape(1,2,1,3)
x


array([[[[1., 1., 1.]],

        [[1., 1., 1.]]]])

In [33]:
y=np.ones(6).reshape(2,1,3,1)
y

array([[[[1.],
         [1.],
         [1.]]],


       [[[1.],
         [1.],
         [1.]]]])

In [34]:
tf.add(x,y)   #final shape = max no.'s of both x,y shapes  = 2 ,2,3,3

<tf.Tensor: shape=(2, 2, 3, 3), dtype=float64, numpy=
array([[[[2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.]],

        [[2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.]]],


       [[[2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.]],

        [[2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.]]]])>

#SUBTRACTION
tf.subtract() :element wise subtraction
 it can subtract list,tuple ,scalar
 tf variable/constant/placeholder/sparsematrix with each other and with scalar and list/tuple.

In [35]:
#scalar subtract
tf.subtract(a,b)

<tf.Tensor: shape=(), dtype=int32, numpy=-10>

In [36]:
#subtract 2 lists
tf.subtract(l1,l2)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 2, -1, -3], dtype=int32)>

In [37]:
#add 2 tuple
tf.subtract(t1,t2)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 2, -1, -3], dtype=int32)>

In [38]:
#subtract list/tuple with scalar
tf.subtract(l1,a)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-6, -5, -4], dtype=int32)>

In [39]:
#subtract 2 list/tuple with diff size ' #NOT POSSIBLE'
lr1=[4,5,6]
lr2=[2,6]
tf.subtract(lr1,lr2)


InvalidArgumentError: {{function_node __wrapped__Sub_device_/job:localhost/replica:0/task:0/device:CPU:0}} Incompatible shapes: [3] vs. [2] [Op:Sub]

In [40]:
#subtract 2 numpy array
tf.subtract(na1,na2)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([ 2, -1, -3])>

In [41]:
#subtract 2 tf constant
tf.subtract(tfc1,tfc2)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 2, -1, -3], dtype=int32)>

In [42]:
#subtract 2 tf variable
tf.subtract(tfv1,tfv2)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 2, -1, -3], dtype=int32)>

In [43]:
#subtract tf constact with scalar
tf.subtract(tfc1,a)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-6, -5, -4], dtype=int32)>

In [44]:
#subtract tf variable with scalar
tf.subtract(tfv1,a)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-6, -5, -4], dtype=int32)>

In [45]:
#subtract 2 numpy array with different size
x=np.ones(6).reshape(1,2,1,3)
y=np.ones(6).reshape(2,1,3,1)
tf.subtract(x,y)

<tf.Tensor: shape=(2, 2, 3, 3), dtype=float64, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]])>

#multiplication
tf.multiply() :element wise multiplication

 it can multiply list,tuple ,scalar

 tf variable/constant/placeholder/sparsematrix with each other and with scalar and list/tuple.

 note:*operator can be used to multiply 2 tensors or (if altleast  1 tensor is available out of 2)


In [46]:
#scalar multiply
tf.multiply(a,b)

<tf.Tensor: shape=(), dtype=int32, numpy=200>

In [47]:
#list mutiply
tf.multiply(l1,l2)  #shape must be same  or second me 1 element ho

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 8, 30, 54], dtype=int32)>

In [58]:
l1*l2  #not useable in case of list / tuple etc we can use in case of tensors

TypeError: can't multiply sequence by non-int of type 'tuple'

In [48]:
#list and scalar
tf.multiply(l1,a)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([40, 50, 60], dtype=int32)>

In [49]:
#multiply 2 numpy array
tf.multiply(na1,na2)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([ 8, 30, 54])>

In [50]:
#multiply numpy array with scalar
tf.multiply(na1,a)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([40, 50, 60])>

In [51]:
#multiply nmumpy array with single element numpy array
tf.multiply(na1,n3)

<tf.Tensor: shape=(1, 3), dtype=int64, numpy=array([[12, 15, 18]])>

In [52]:
#multiply 2 tf constants
tf.multiply(tfc1,tfc2)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 8, 30, 54], dtype=int32)>

In [57]:
tfc1*tfc2

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 8, 30, 54], dtype=int32)>

In [53]:
#multiplyb 2 tf variable
tf.multiply(tfv1,tfv2)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 8, 30, 54], dtype=int32)>

In [59]:
tfv1*tfv2

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 8, 30, 54], dtype=int32)>

In [54]:
#multiply tf constant with scalar
tf.multiply(tfc1,a)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([40, 50, 60], dtype=int32)>

In [55]:
#multipy variable with scalar
tf.multiply(tfv1,a)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([40, 50, 60], dtype=int32)>

In [56]:
#multiply numpy array of diff shapes but no. of elements same
x=np.ones(6).reshape(1,2,1,3)
y=np.ones(6).reshape(2,1,3,1)
tf.multiply(x,y)

<tf.Tensor: shape=(2, 2, 3, 3), dtype=float64, numpy=
array([[[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]]])>

#DIVISION
tf.divide() :element wise DIVISION

it can divide list,tuple ,scalar

tf variable/constant/placeholder/sparsematrix with each other and with scalar and list/tuple.

note: / exact or // GI operator can be used to dividey 2 tensors or (if altleast 1 tensor is available out of  = output also tensor)



(but if both scalar or both numpy or none is tensor output:scalar,numpy respectively)




In [60]:
#scalar division'
tf.divide(a,b)

<tf.Tensor: shape=(), dtype=float64, numpy=0.5>

In [68]:
l1,l2

((4, 5, 6), (2, 6, 9))

In [61]:
#list division
tf.divide(l1,l2)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([2.        , 0.83333333, 0.66666667])>

In [63]:
#tuple divison
tf.divide(t1,t2)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([2.        , 0.83333333, 0.66666667])>

In [64]:
a/b

0.5

In [65]:
a//b

0

In [66]:
l1/l2  #notb possible

TypeError: unsupported operand type(s) for /: 'tuple' and 'tuple'

In [67]:
# divide list with scalar
tf.divide(l1,a)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.4, 0.5, 0.6])>

In [72]:
#divide list with single element list
l3=[4]
tf.divide(l1,l3)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1.  , 1.25, 1.5 ])>

In [69]:
#divide tuple with scalar
tf.divide(t1,a)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.4, 0.5, 0.6])>

In [70]:
#divide 2 numpy array
tf.divide(na1,na2)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([2.        , 0.83333333, 0.66666667])>

In [71]:
#divide numpy array with scalar
tf.divide(na1,a)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.4, 0.5, 0.6])>

In [73]:
#divide numpy array of diff. shape
x=np.ones(6).reshape(1,2,1,3)
y=np.ones(6).reshape(2,1,3,1)
tf.divide(x,y)

<tf.Tensor: shape=(2, 2, 3, 3), dtype=float64, numpy=
array([[[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]]])>

In [76]:
#division of 2 constant tf
tf.divide(tfc1,tfc2)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([2.        , 0.83333333, 0.66666667])>

In [77]:
#division of 2variable
tf.divide(tfv1,tfv2)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([2.        , 0.83333333, 0.66666667])>

In [74]:
x/y

array([[[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]]])