<a href="https://colab.research.google.com/github/Amritpal-nitj/Tensorflow/blob/main/creatingconstantvariable.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#CREATING CONSTANT VARIABLE IN TENSORFLOW 2.x

In [ ]:
import tensorflow as tf  #importing tensorflow

In [ ]:
tf.__version__ #checking version

'2.18.0'

In [ ]:
tf.test.is_gpu_available() #checking gpu availability

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


False

"mostly syntax same as numpy"


Use: While building neural network graph need constant varibale like input data,
it never change while training

Create integer constant

In [ ]:
constantint=tf.constant(10)
constantint

<tf.Tensor: shape=(), dtype=int32, numpy=10>

create float constant

In [ ]:
constantflo=tf.constant(10.2)
constantflo

<tf.Tensor: shape=(), dtype=float32, numpy=10.199999809265137>

create string constant

In [ ]:
constantstr=tf.constant("Punjab")
constantstr

<tf.Tensor: shape=(), dtype=string, numpy=b'Punjab'>

create bool constant

In [ ]:
constantbool=tf.constant(True)
constantbool

<tf.Tensor: shape=(), dtype=bool, numpy=True>

Create constant numpy array/list/tuple

In [ ]:
import numpy as np

In [ ]:
np_array=tf.constant(np.array([1,2,3,4]))
np_array

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([1, 2, 3, 4])>

In [ ]:
#create 1d  constant
t_1d=tf.constant([1,2,3,4])
t_1d


<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [ ]:
#create 2d  constant
t_2d=tf.constant([[1,2,4],[4,5,6]])
t_2d

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 4],
       [4, 5, 6]], dtype=int32)>

creating 2 d array constant with single list

In [ ]:
t_2d=tf.constant([1,2,3,4],shape=(2,2))  #2 row 2 column
t_2d

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
#create Nd  constant
t_3d=tf.constant([[[1,2,4],[4,5,6],[5,6,9]]])     shape indiacate  1 ,3 unit,3element
t_3d

<tf.Tensor: shape=(1, 3, 3), dtype=int32, numpy=
array([[[1, 2, 4],
        [4, 5, 6],
        [5, 6, 9]]], dtype=int32)>

In [ ]:
type(t_3d)

tensorflow.python.framework.ops.EagerTensor

In [ ]:
t_3d.shape

TensorShape([1, 3, 3])

#Access constant value

In [ ]:
t_2d.numpy()



array([[1, 2],
       [3, 4]], dtype=int32)

In [ ]:
t_2d.numpy()[0,1]

np.int32(2)

In [ ]:
t_2d.dtype

tf.int32