<a href="https://colab.research.google.com/github/Amritpal-nitj/Tensorflow/blob/main/CreatesSparseTensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#HOW TO CREATE SPARSE TENSOR IN TENSORFLOW2
max values 0 ,enable effiecient storage

*Tensor that contain mostly zero values are called sparse tensor .*

When working with tensors that contain a lot of zero values, it is important to store them in a space-
and time-efficient manner.
Sparse tensors enable efficient storage and processing of tensors that contain a lot of zero values.
Sparse tensors are used extensively in encoding schemes like TF-IDF as part of data pre-processing in
NLP applications and for pre-processing images with a lot of dark pixels in computer vision
applications.


Currently, sparse tensors in TensorFlow are encoded using the coordinate list (C0O)] format.

The C00 encoding for sparse tensors is comprised of:

values: A 1D tensor with shape [N] containing all nonzero values.

indices: A 2D tensor with shape [N, rank], containing the indices of the nonzero values.

dense_shape: A 1D tensor with shape [rank], specifying the shape of the tensor.

A nonzero value in the context of a tf.SparseTensor is a value that's not explicitly encoded.

CREATE TENSORFLOW SPARSE TENSOR

In [1]:
import tensorflow as tf

In [2]:
st1=tf.SparseTensor(indices=[[0,3],[2,4]],values=[10,20],dense_shape=[3,10])
st1

SparseTensor(indices=tf.Tensor(
[[0 3]
 [2 4]], shape=(2, 2), dtype=int64), values=tf.Tensor([10 20], shape=(2,), dtype=int32), dense_shape=tf.Tensor([ 3 10], shape=(2,), dtype=int64))

In [3]:
print(st1)

SparseTensor(indices=tf.Tensor(
[[0 3]
 [2 4]], shape=(2, 2), dtype=int64), values=tf.Tensor([10 20], shape=(2,), dtype=int32), dense_shape=tf.Tensor([ 3 10], shape=(2,), dtype=int64))


CREATING SPARSE TENSOR FROM DENSE

In [6]:
import numpy as np
np_array=np.array([[1,0,0,0],
                   [0,0,0,0],
                   [0,0,2,0],
                   [0,0,0,4] ])
np_array

array([[1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 4]])

In [7]:
st2_fd=tf.sparse.from_dense(np_array)
st2_fd

SparseTensor(indices=tf.Tensor(
[[0 0]
 [2 2]
 [3 3]], shape=(3, 2), dtype=int64), values=tf.Tensor([1 2 4], shape=(3,), dtype=int64), dense_shape=tf.Tensor([4 4], shape=(2,), dtype=int64))

Extract indices,values,dense_shape of SparseTensor

In [8]:
st1.indices.numpy().tolist()

[[0, 3], [2, 4]]

In [9]:
st1.values.numpy().tolist()

[10, 20]

In [10]:
st1.dense_shape.numpy().tolist()

[3, 10]

FROM SPARSETENSOR TO DENSE

In [12]:
st2_td=tf.sparse.to_dense(st2_fd)
st2_td

<tf.Tensor: shape=(4, 4), dtype=int64, numpy=
array([[1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 4]])>

In [13]:
#convert dense tensor to numpy
st2_td.numpy()

array([[1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 4]])

#mathematical operation of sparse tensor
because sparse tensor will take less time

In [14]:
tf_add=tf.sparse.add(st1,st1)
tf_add

SparseTensor(indices=tf.Tensor(
[[0 3]
 [2 4]], shape=(2, 2), dtype=int64), values=tf.Tensor([20 40], shape=(2,), dtype=int32), dense_shape=tf.Tensor([ 3 10], shape=(2,), dtype=int64))

In [15]:
#now we can also covert it into dense
tf_add_td=tf.sparse.to_dense(tf_add)
tf_add_td

<tf.Tensor: shape=(3, 10), dtype=int32, numpy=
array([[ 0,  0,  0, 20,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 40,  0,  0,  0,  0,  0]], dtype=int32)>