<a href="https://colab.research.google.com/github/Amritpal-nitj/Tensorflow/blob/main/minmax.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

How Get Maximum value from Tensors in
TensorFlow?

tf.maximum() : Returns the maximum value by comparing of x and y (i.e. x> y ? x : y) element-
wise.
It work with list, tuple, scaler, Numpy array
tf variable/constant/placeholder/SparceMatrix with each other and with scaler and with list/tuple

Syntax: tf.maximum(x, y, name=None)

Args
x=> A Tensor. Must be one of the following types: bfloat16, half, float32,
float64, int8, uint8, int16, uint16, int32, uint32, int64, uint64.
y=> A Tensor. Must have the same type as x.

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
#get max of scalar
x=1
y=4
tf.maximum(x,y)

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [7]:
tf.maximum(x,y).numpy()

np.int32(4)

In [8]:
#for lists
l1=[1,2,3,4,5]
l2=[2,3,4,5,6]
tf.maximum(l1,l2)


<tf.Tensor: shape=(5,), dtype=int32, numpy=array([2, 3, 4, 5, 6], dtype=int32)>

In [9]:
#for tuple
t1=(1,2,3,4,5)
t2=(2,3,4,5,6)
tf.maximum(t1,t2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([2, 3, 4, 5, 6], dtype=int32)>

In [10]:
#for tf constants
tfc1=tf.constant([1,2,3,4,5])
tfc2=tf.constant([2,3,4,5,6])
tf.maximum(tfc1,tfc2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([2, 3, 4, 5, 6], dtype=int32)>

In [16]:
#for tf constants with scalar
tfc1=tf.constant([1,2,3,4,5])
x=8
tf.maximum(tfc1,x)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([8, 8, 8, 8, 8], dtype=int32)>

In [11]:
#for tf variables
tfv1=tf.Variable([1,2,3,4,5])
tfv2=tf.Variable([2,3,4,5,6])
tf.maximum(tfv1,tfv2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([2, 3, 4, 5, 6], dtype=int32)>

In [12]:
#for numpy arrays
np1=np.array([1,2,3,4,5])
np2=np.array([2,3,4,5,6])
tf.maximum(np1,np2)

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([2, 3, 4, 5, 6])>

In [15]:
#get max value of list/tuple with scalar or single element list
l1=[1,2,3,4,10,15]    #not valid for lists of diff size
x=8
tf.maximum(l1,x)

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([ 8,  8,  8,  8, 10, 15], dtype=int32)>

#How Get Minimum value from Tensors inTensorFlow?

tf.minimum() : Returns the minimum value by comparing of x and y (i.e. x>y ? x: y) element-
wise.

It work with list, tuple, scaler, Numpy array

tf variable/constant/placeholder/SparceMatrix with each other and with scaler and with list/tuple

Syntax: tf.minimum(x, y, name=None)

In [17]:
#get min of scalar
x=1
y=4
tf.minimum(x,y)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [18]:
#for lists
l1=[1,2,3,4,5]
l2=[2,3,4,5,6]
tf.minimum(l1,l2)


<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>

In [19]:
#for tuple
t1=(1,2,3,4,5)
t2=(2,3,4,5,6)
tf.minimum(t1,t2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>

In [20]:
#for tf constants
tfc1=tf.constant([1,2,3,4,5])
tfc2=tf.constant([2,3,4,5,6])
tf.minimum(tfc1,tfc2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>

In [21]:
#for tf constants with scalar
tfc1=tf.constant([1,2,3,4,5])
x=8
tf.minimum(tfc1,x)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>

In [22]:
#for tf variables
tfv1=tf.Variable([1,2,3,4,5])
tfv2=tf.Variable([2,3,4,5,6])
tf.minimum(tfv1,tfv2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>

In [23]:
#for numpy arrays
np1=np.array([1,2,3,4,5])
np2=np.array([2,3,4,5,6])
tf.minimum(np1,np2)

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([1, 2, 3, 4, 5])>

In [24]:
#get min value of list/tuple with scalar or single element list
l1=[1,2,3,4,10,15]    #not valid for lists of diff size
x=8
tf.minimum(l1,x)

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 2, 3, 4, 8, 8], dtype=int32)>