<a href="https://colab.research.google.com/github/Amritpal-nitj/Tensorflow/blob/main/power.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

How Calculate Power of Tensors in TensorFlow?

tf.pow() : Calculate the power of one value to another, Element wise power calculation
It can be give power of scaler, Numpy array
It allow tf variable/constant/placeholder/SparceMatrix with Specific datatype

Data Type : float16, float32, float64, int32, int64, complex64, or complex128.

Note: Don't pass data in integer format, it will through error




tf.pow(jiska nikalna,kitna power)

In [3]:
import tensorflow as tf
import numpy as np

In [2]:
#pow of scalar
a=4
b=2
tf.pow(a,b)


<tf.Tensor: shape=(), dtype=int32, numpy=16>

In [4]:
#power of numpy array
na1=np.array([1,2,4],dtype=np.float64)
tf.pow(na1,2)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 1.,  4., 16.])>

In [5]:
na1=np.array([2,3,4],dtype=np.float64)
na2=np.array([2,4,5],dtype=np.float64)
tf.pow(na1,na2)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([   4.,   81., 1024.])>

In [7]:
y=np.ones(6).reshape(2,1,3,1)*4
y

array([[[[4.],
         [4.],
         [4.]]],


       [[[4.],
         [4.],
         [4.]]]])

In [8]:
tf.pow(y,3)

<tf.Tensor: shape=(2, 1, 3, 1), dtype=float64, numpy=
array([[[[64.],
         [64.],
         [64.]]],


       [[[64.],
         [64.],
         [64.]]]])>

In [11]:
l1=[2,5,6]
l2=[5,2,4]
tf.pow(l1,l2)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([  32,   25, 1296], dtype=int32)>

In [12]:
#power of tf constant
a=tf.constant([1,2,3],dtype=tf.float64)
b=tf.constant([2,3,4],dtype=tf.float64)
tf.pow(a,b)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 1.,  8., 81.])>

In [13]:
#power of tf variable
c=tf.Variable([1,2,3],dtype=tf.float64)
d=tf.Variable([2,3,4],dtype=tf.float64)
tf.pow(c,d)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 1.,  8., 81.])>