<a href="https://colab.research.google.com/github/Amritpal-nitj/Tensorflow/blob/main/sqrt.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

How to calculate Square Root of Tensors in
TensorFlow?

tf.sqrt() : Calculate Element wise suare root of numpy array and TF tensor,
It can be give sqrt of list, tuple, scaler
It allow tf variable/constant/placeholder/SparceMatrix with Specific datatype

Data Type : bfloat16, half, float32, float64, complex64, complex128.

Note: Don't give 'int' data type, tf.sqrt() will through error

In [2]:
import numpy as np
import tensorflow as tf

In [3]:
#scalar
tf.sqrt(9.0)

<tf.Tensor: shape=(), dtype=float32, numpy=3.0>

In [4]:
#sqrt of list
l1=[4.0,9.0,6.0]
tf.sqrt(l1)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([2.       , 3.       , 2.4494898], dtype=float32)>

In [5]:
#sqrt of tuple
t1=(4.0,16.0,19.0)
tf.sqrt(t1)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([2.      , 4.      , 4.358899], dtype=float32)>

In [8]:
#sqrt of numpy array
n1=np.array([4,16,78],dtype=np.float64)
tf.sqrt(n1)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([2.        , 4.        , 8.83176087])>

In [12]:
#
y=np.ones(6).reshape(2,1,3,1)*4
y

array([[[[4.],
         [4.],
         [4.]]],


       [[[4.],
         [4.],
         [4.]]]])

In [13]:
y.dtype

dtype('float64')

In [14]:
tf.sqrt(y)

<tf.Tensor: shape=(2, 1, 3, 1), dtype=float64, numpy=
array([[[[2.],
         [2.],
         [2.]]],


       [[[2.],
         [2.],
         [2.]]]])>

#sqrt of tensor

In [15]:
tf.sqrt(tf.convert_to_tensor(4,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

In [16]:
tf.sqrt(tf.convert_to_tensor([4,9,16,56],dtype=tf.float32))

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([2.      , 3.      , 4.      , 7.483315], dtype=float32)>

sqrt of contsant tensor

In [17]:
tfc1=tf.constant([4,9,16,25],dtype=tf.float32)
tf.sqrt(tfc1)


<tf.Tensor: shape=(4,), dtype=float32, numpy=array([2., 3., 4., 5.], dtype=float32)>

In [18]:
#sqrt of variable
tfv1=tf.Variable([4,9,16,25],dtype=tf.float32)
tf.sqrt(tfv1)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([2., 3., 4., 5.], dtype=float32)>